In [13]:
import pandas as pd

df = pd.DataFrame({
      '日付':
      ['2023-05-17', '2023-05-18', '2023-05-19', '2023-05-20', '2023-05-21'],
    '社員名': ['山田', '佐藤', '鈴木', '田中', '高橋'],
    '売上': [100, 200, 150, 300, 250],
    '部門': ['メーカー', '代理店', 'メーカー', '商社', '代理店'],
})


df['平均売上'] = df['売上'].mean()

def performance(level):
  result = '';
  if level >=df['平均売上'].mean()+50:
    result = 'A';
  elif level >=df['平均売上'].mean():
    result = 'B';
  else:
    result = 'C';
  return result

df['業績ランク'] = df['売上'].apply(performance)

writer = pd.ExcelWriter('業績.xlsx')
df.to_excel(writer,sheet_name = 'sheet1, index=False')
writer.close()

In [ ]:
import pandas as pd

df = pd.DataFrame({
      '日付':
      ['2023-05-17', '2023-05-18', '2023-05-19', '2023-05-20', '2023-05-21'],
    '社員名': ['山田', '佐藤', '鈴木', '田中', '高橋'],
    '売上': [100, 200, 150, 300, 250],
    '部門': ['メーカー', '代理店', 'メーカー', '商社', '代理店'],
})

df['平均売上'] = df['売上'].mean()

df['平均売上']

df

           日付 社員名   売上    部門   平均売上
0  2023-05-17  山田  100  メーカー  200.0
1  2023-05-18  佐藤  200   代理店  200.0
2  2023-05-19  鈴木  150  メーカー  200.0
3  2023-05-20  田中  300    商社  200.0
4  2023-05-21  高橋  250   代理店  200.0

In [ ]:
df['平均売上'] = df['売上'].mean()

df['平均売上']

0    200.0
1    200.0
2    200.0
3    200.0
4    200.0
Name: 平均売上, dtype: float64